### ISSUE TITLE
Example code does not work. IllegalArgumentException occur.

### ISSUE THREAD

**Issue by fatrow** [weavejester/re-rand#1]
Thanks for great library!
I get a following error.
user> (re-rand #"[A-Z]{4}")
java.lang.IllegalArgumentException: Wrong number of args passed to: core$apply

This error occurred at (map apply fs) in re-rand.parser.rules/pattern, but I couldn't fix it.
Thanks.

**Comment by weavejester** [comment]
It looks like the behaviour of `apply` has changed since the early days of Clojure. I fixed the bug, and I've updated the repository to use Leiningen.

Sorry for taking so long to sort this out. I forgot to make a note of it on my TODO list.

**Comment by fatrow** [comment]
Hi weavejester.
Thank you! It works fine.
