### ISSUE TITLE
Logical OR (| char) doesn't work

### ISSUE THREAD

**Issue by bjeanes** [weavejester/re-rand#2]
Hi,

The following re-rand call does not work as expected:

(re-rand #"(19|20)\d\d")

It will just generate something like 19|2014 or 19|2099

Is this a bug or is there another way to achieve the desired behaviour?

**Comment by weavejester** [comment]
It's a missing piece of functionality. Patches to implement this are welcome.

**Comment by jimpil** [comment]
How would one go about implementing this? I feel this is quite important but I don't know where to start...The code is not big but I wouldn't know where to look! Could you provide any sort of hint or insight to get me started? Thanks a lot...I really do need a lib like this and I wouldn't want to fall back to Java once more! :)
